/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#00eefc",
        "on-secondary-fixed": "#40009b",
        "secondary": "#ac8aff",
        "tertiary-fixed-dim": "#51a7fe",
        "on-error-container": "#ffa8a3",
        "on-tertiary": "#002e52",
        "secondary-dim": "#8455ef",
        "on-surface": "#dee5ff",
        "error-container": "#9f0519",
        "on-background": "#dee5ff",
        "on-primary-fixed": "#003f43",
        "secondary-fixed": "#dac9ff",
        "on-tertiary-fixed-variant": "#003b68",
        "on-tertiary-fixed": "#001930",
        "inverse-primary": "#006a71",
        "surface-container-low": "#091328",
        "on-surface-variant": "#a3aac4",
        "secondary-fixed-dim": "#ceb9ff",
        "inverse-surface": "#faf8ff",
        "surface-container-lowest": "#000000",
        "error-dim": "#d7383b",
        "surface-container-high": "#141f38",
        "on-primary-fixed-variant": "#005e64",
        "surface-bright": "#1f2b49",
        "on-secondary-fixed-variant": "#5f28c8",
        "secondary-container": "#5516be",
        "inverse-on-surface": "#4d556b",
        "primary-fixed-dim": "#00deec",
        "primary": "#8ff5ff",
        "surface-container": "#0f1930",
        "primary-fixed": "#00eefc",
        "on-secondary": "#280067",
        "outline-variant": "#40485d",
        "on-error": "#490006",
        "surface-variant": "#192540",
        "surface-container-highest": "#192540",
        "primary-dim": "#00deec",
        "surface-tint": "#8ff5ff",
        "tertiary-container": "#4aa2f9",
        "on-primary": "#005d63",
        "surface": "#060e20",
        "tertiary-fixed": "#72b5ff",
        "on-primary-container": "#005359",
        "tertiary": "#65afff",
        "surface-dim": "#060e20",
        "error": "#ff716c",
        "background": "#060e20",
        "on-tertiary-container": "#00213e",
        "outline": "#6d758c",
        "on-secondary-container": "#d9c8ff",
        "tertiary-dim": "#4aa2f9"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"],
        "sans": ["Inter", "sans-serif"],
        "space-grotesk": ["Space Grotesk"]
      }
    },
  },
  plugins: [],
}

